spring:
  application.name: hhplus-tdd
#  jackson:
#    serialization:
#      indent_output: true
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: always

logging:
  level:
    org.springframework.web: DEBUG

lock:
  timeout: 3